version: '3'
services:
  app:
   image: vishalm04/notejam
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DB_ENGINE=django.db.backends.postgresql_psycopg2
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
